import './legacy'
import './appUpdaterBridge'
import './pageScenarioScheduleBridge'
import './pageWallFiniteBridge'
import './changeInfoBridge'

export type { PageAutoApi } from './legacy'
export type { AppUpdaterPreloadApi } from './appUpdaterBridge'
export type { PageScenarioSchedulePreloadApi } from './pageScenarioScheduleBridge'
export type { PageWallFinitePreloadApi } from './pageWallFiniteBridge'
export type { ChangeInfoPreloadApi } from './changeInfoBridge'
