import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const bindingScopeSource = readFileSync(new URL('./PageBusinessBindingScope.tsx', import.meta.url), 'utf8')
const bindingCssSource = readFileSync(new URL('./pageBusinessBindings.css', import.meta.url), 'utf8')
const wallCssSource = readFileSync(new URL('./pageWallWorkspace.css', import.meta.url), 'utf8')
const groupManagerSource = readFileSync(new URL('./PageTabsManagerV2.tsx', import.meta.url), 'utf8')
const wallSource = readFileSync(new URL('./PageWallWorkspace.tsx', import.meta.url), 'utf8')
const coreSource = readFileSync(new URL('./PageBusinessWorkspaceCore.tsx', import.meta.url), 'utf8')
const actionSource = readFileSync(new URL('../actions/ActionWorkspace.tsx', import.meta.url), 'utf8')

describe('Page business binding regression', () => {
  it('does not synchronize the active Page through hidden DOM clicks or synthetic change events', () => {
    expect(bindingScopeSource).not.toContain("querySelectorAll<HTMLButtonElement>('.page-tab-chip')")
    expect(bindingScopeSource).not.toContain("dispatchEvent(new Event('change'")
    expect(bindingScopeSource).not.toContain('setInterval(sync, 150)')
    expect(bindingScopeSource).toContain('<PageTabsManager activePageId={activePageId} scoped />')
    expect(bindingScopeSource).toContain('<PageWallWorkspace activePageId={activePageId} scoped />')
  })

  it('keeps the scoped Page business child on a definite-height layout chain', () => {
    expect(bindingScopeSource).toContain('className="page-business-binding-content"')
    expect(bindingCssSource).toMatch(/\.page-business-binding-scope\s*\{[^}]*height:\s*100%;[^}]*display:\s*flex;/s)
    const contentRule = bindingCssSource.match(/\.page-business-binding-content\s*\{([^}]*)\}/s)?.[1] ?? ''
    expect(contentRule).toContain('min-height: 0;')
    expect(contentRule).toContain('flex: 1 1 0;')
    expect(bindingCssSource).toMatch(/\.page-business-scoped-child[\s\S]*height:\s*100%;/)
    expect(bindingCssSource).toContain('.page-business-scoped-child > .page-tabs-manager')
  })

  it('drives Đăng Nhóm config and runtime from the bound Page id', () => {
    expect(groupManagerSource).toContain('activePageId: controlledActiveId')
    expect(groupManagerSource).toContain('const nextActive = controlledActiveId ?? preferredId ?? activeId')
    expect(groupManagerSource).toContain('!scoped ? <div className="page-tabs-strip"')
    expect(coreSource).toContain('CurrentPageRuntimeActions({ activePageId }')
    expect(coreSource).toContain("action({ pageTabId: activePageId })")
    expect(coreSource).not.toContain("findIndex((button) => button.classList.contains('active'))")
  })

  it('keeps Đăng Tường on the bound Page and uses the finite Wall runtime instead of legacy recurring modes', () => {
    expect(wallSource).toContain('activePageId: controlledPageId')
    expect(wallSource).toContain("type Mode = 'now' | 'schedule'")
    expect(wallSource).toContain('window.pageWallFinite.getDashboard')
    expect(wallSource).toContain('window.pageWallFinite.runNow')
    expect(wallSource).toContain('window.pageWallFinite.saveSchedule')
    expect(wallSource).toContain('window.pageWallFinite.deleteSchedule')
    expect(wallSource).toContain('buildPageWallFiniteTasks')
    expect(wallSource).toContain('Đăng ngay')
    expect(wallSource).toContain('Lịch chạy')
    expect(wallSource).not.toContain('Hẹn 1 lần')
    expect(wallSource).not.toContain('parsePageWallBusinessSchedule')
    expect(wallSource).not.toContain('serializePageWallBusinessSchedule')
    expect(wallSource).not.toContain('getPageWallRecurringPlan')
    expect(wallSource).not.toContain('savePageWallRecurringPlan')
    expect(wallSource).not.toContain('clearPageWallRecurringPlan')
    expect(actionSource).toContain('savedWorkspaces.filter((workspace) => !isPageBusinessWorkspace(workspace))')
  })

  it('makes the account grid actually selectable by row and checkbox with visible selected state', () => {
    expect(wallSource).toContain('data-account-id={account.accountId}')
    expect(wallSource).toContain("selected ? 'selected' : ''")
    expect(wallSource).toContain('if (runnable && !busy) toggleAccount(account.accountId)')
    expect(wallSource).toContain('event.stopPropagation()')
    expect(wallCssSource).toContain('.page-wall-account-table tbody tr.selected')
    expect(wallCssSource).toMatch(/\.page-wall-account-table tbody tr\s*\{[^}]*cursor:\s*pointer;/s)
  })

  it('makes the selected canonical post explicit and edits the common library instead of a Wall-only store', () => {
    expect(wallSource).toContain('data-testid="page-wall-selected-post"')
    expect(wallSource).toContain('Chọn từ Thư viện')
    expect(wallSource).toContain('Thêm bài')
    expect(wallSource).toContain('Sửa bài')
    expect(wallSource).toContain('Bỏ chọn')
    expect(wallSource).toContain('window.pageAuto.createContentLibraryItem')
    expect(wallSource).toContain('window.pageAuto.updateContentLibraryItem')
    expect(wallSource).toContain('CANONICAL_CONTENT_LIBRARY_SET_ID')
    expect(wallSource).not.toContain('createPageTabPost')
  })

  it('uses a FPlus-style complete schedule dialog with post, accounts, multi-time and concurrency', () => {
    expect(wallSource).toContain('aria-label="Thiết lập lịch đăng"')
    expect(wallSource).toContain('1. Chọn bài viết')
    expect(wallSource).toContain('2. Thời gian đăng bài')
    expect(wallSource).toContain('3. Chọn tài khoản muốn đăng')
    expect(wallSource).toContain('+ Thêm giờ')
    expect(wallSource).toContain('+ Thêm lịch')
    expect(wallSource).toContain('TK song song')
    expect(wallSource).toContain('taskCount: scheduleDraft.accountIds.length')
    expect(wallSource).not.toContain('Số task')
    expect(wallSource).not.toContain('Lưu kế hoạch')
  })

  it('renders Đăng Tường as the locked native three-region workspace', () => {
    expect(bindingScopeSource).not.toContain('page-wall-group-layout')
    expect(bindingScopeSource).not.toContain('openWallTool')
    expect(bindingScopeSource).not.toContain('querySelector<HTMLElement>')
    expect(wallSource).toContain('data-testid="page-wall-three-regions"')
    expect(wallSource).toContain('data-testid="page-wall-region-accounts"')
    expect(wallSource).toContain('data-testid="page-wall-region-content"')
    expect(wallSource).toContain('data-testid="page-wall-region-control"')
    expect(wallSource).toContain('Chọn tất cả')
    expect(wallSource).toContain('Bỏ chọn')
    expect(wallSource).toContain('TK chạy song song')
    expect(wallSource).toContain('Chạy đúng các TK đang tick')
    expect(wallSource).toContain('data-testid="page-wall-plan-list"')
    expect(wallCssSource).toContain('.page-wall-three-regions')
    expect(wallCssSource).toContain('grid-template-columns:')
    expect(wallCssSource).toContain('.page-wall-region')
    expect(wallCssSource).toContain('.page-wall-mode-tabs')
  })
})
