import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const appSource = readFileSync(new URL('../App.tsx', import.meta.url), 'utf8')
const workspaceSource = readFileSync(new URL('./ActionWorkspace.tsx', import.meta.url), 'utf8')
const registrySource = readFileSync(new URL('./actionWorkspaceRegistry.ts', import.meta.url), 'utf8')
const interactionSource = readFileSync(new URL('./InteractionWorkspace.tsx', import.meta.url), 'utf8')
const interactionModelSource = readFileSync(new URL('./interactionWorkspaceModel.ts', import.meta.url), 'utf8')
const accountPickerSource = readFileSync(new URL('./AccountBindingPickerModal.tsx', import.meta.url), 'utf8')

describe('Action workspace shell', () => {
  it('uses Hành động as the semantic main route', () => {
    expect(appSource).toContain("{ id: 'actions', label: 'Hành động' }")
    expect(appSource).not.toContain("{ id: 'scenarios', label: 'Kịch Bản' }")
    expect(appSource).toContain("activeRoute === 'actions' ? 'HÀNH ĐỘNG'")
    expect(appSource).toContain("activeRoute === 'actions' ? <ActionWorkspace />")
  })

  it('keeps Kịch bản fixed, persists workspace tabs and restores the last active tab', () => {
    expect(workspaceSource).toContain('<ScenarioWorkspace />')
    expect(workspaceSource).toContain('Kịch bản')
    expect(workspaceSource).toContain('+ Tab')
    expect(workspaceSource).toContain('Chọn tab nghiệp vụ')
    expect(workspaceSource).toContain('window.pageAuto.listActionWorkspaces()')
    expect(workspaceSource).toContain('window.pageAuto.createActionWorkspace')
    expect(workspaceSource).toContain('window.pageAuto.deleteActionWorkspace')
    expect(workspaceSource).toContain("ACTIVE_TAB_STORAGE_KEY = 'page-auto:actions:active-tab'")
    expect(workspaceSource).toContain('window.localStorage.getItem(ACTIVE_TAB_STORAGE_KEY)')
    expect(workspaceSource).toContain('window.localStorage.setItem(ACTIVE_TAB_STORAGE_KEY, activeTabId)')
    expect(workspaceSource).toContain('<InteractionWorkspace workspace={tab} availableAccounts={accounts}')
    expect(registrySource).toContain("id: 'interaction'")
    expect(registrySource).toContain("label: 'Tương tác'")
  })

  it('uses Page-Tab-style account picker and rolling account concurrency while preserving runtime controls', () => {
    expect(interactionSource).toContain('+ Thêm tài khoản')
    expect(interactionSource).toContain('<AccountBindingPickerModal')
    expect(accountPickerSource).toContain('pt-account-picker-modal')
    expect(accountPickerSource).toContain('Tìm UID, tên, email, note…')
    expect(accountPickerSource).toContain('Tất cả trạng thái')
    expect(accountPickerSource).toContain('Tất cả category')
    expect(accountPickerSource).toContain('Chọn đang lọc')
    expect(accountPickerSource).toContain('pt-account-picker-grid')
    expect(interactionSource).toContain('interaction-target-compact')
    expect(interactionSource).toContain('Chạy bằng Page')
    expect(interactionSource).toContain('Nhập UID Page')
    expect(interactionSource).toContain('TK song song')
    expect(interactionSource).toContain('accountConcurrency')
    expect(interactionSource).toContain('MAX_INTERACTION_ACCOUNT_CONCURRENCY')
    expect(interactionSource).toContain('Pool cuốn chiếu')
    expect(interactionSource).not.toContain('Khóa = 1')
    expect(interactionSource).toContain('window.pageAuto.updateActionWorkspace')
    expect(interactionSource).toContain('Lưu cấu hình')
    expect(interactionModelSource).toContain("label: 'Like / Reaction'")
    expect(interactionModelSource).toContain("pushModule(actionTypes, 'switch_page')")
    expect(interactionSource).toContain('Kế hoạch module')
    expect(interactionSource).toContain("runCommand('start')")
    expect(interactionSource).toContain("runCommand('pause')")
    expect(interactionSource).toContain("runCommand('resume')")
    expect(interactionSource).toContain("runCommand('stop')")
  })
})
